server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://loki:3100/loki/api/v1/push
    batchsize: 1048576 
    batchwait: 2s      
scrape_configs:
  - job_name: recipes-app
    static_configs:
      - targets:
          - localhost
        labels:
          job: recipes-app
          __path__: /var/log/*log