server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://loki:3100/loki/api/v1/push
scrape_configs:
  - job_name: recipes-app
    static_configs:
      - targets:
          - localhost
        labels:
          job: recipes-app
          __path__: /var/log/*log
    pipeline_stages:
      - json:
          expressions:
           message: message
      - regex:
          expression: "and name (\\S+)"
      - labels:
          recipe_name: