{
 "title": "Recipes Loki Logs",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "filter" }
  ]
 },
 "panels": [
  {
   "title": "Level Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({\r\n    filename=\"/var/log/recipes-json.log\"} |= `$filter` | json | __error__=`` [$__range]))"
    }
   ]
  },
  {
   "title": "Top 10 Most Viewed Recipes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 10, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,sum by(message) (count_over_time({job=\"recipes-app\", filename=\"/var/log/recipes-json.log\"} |= `$filter` |= `receta - ` | json | __error__=`` [$__range])))"
    }
   ]
  },
  {
   "title": "Registered Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by() (count_over_time({job=\"recipes-app\", filename=\"/var/log/recipes-json.log\"} |= `$filter` |= `registrado ` | json | __error__=`` [$__range]))"
    }
   ]
  },
  {
   "title": "Upload Recipes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by() (count_over_time({job=\"recipes-app\", filename=\"/var/log/recipes-json.log\"} |= `$filter` |= `ha creado la receta ` | json | __error__=`` [$__range]))"
    }
   ]
  },
  {
   "title": "Logs Info",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"recipes-app\", filename=\"/var/log/recipes-json.log\"} |= `$filter`  | json  | __error__= ``"
    }
   ]
  }
 ]
}